"""initial schema: all 22 tables

Revision ID: fae0062d7af9
Revises: 
Create Date: 2026-09-27 12:22:09.186328
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Portable JSON: JSONB on PostgreSQL, plain JSON on SQLite (tests only).
JSONB_COL = postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite")

revision: str = 'fae0062d7af9'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('customer', 'farmer', 'business', 'rider', 'admin', native_enum=False, length=40), nullable=False),
    sa.Column('address_line', sa.String(length=512), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'deactivated', native_enum=False, length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_table('admin_action_log',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_admin_action_log_action'), 'admin_action_log', ['action'], unique=False)
    op.create_index(op.f('ix_admin_action_log_admin_id'), 'admin_action_log', ['admin_id'], unique=False)
    op.create_table('cart',
    sa.Column('cart_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cart_data', JSONB_COL, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('cart_id')
    )
    op.create_index(op.f('ix_cart_user_id'), 'cart', ['user_id'], unique=True)
    op.create_table('chatbot_message',
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('sender', sa.Enum('user', 'bot', native_enum=False, length=40), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_chatbot_message_session_id'), 'chatbot_message', ['session_id'], unique=False)
    op.create_index(op.f('ix_chatbot_message_user_id'), 'chatbot_message', ['user_id'], unique=False)
    op.create_table('farm',
    sa.Column('farm_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('farm_name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=512), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('capacity_liters', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('established_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.Enum('pending', 'verified', 'rejected', native_enum=False, length=40), nullable=False),
    sa.Column('rating_avg', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('farm_id')
    )
    op.create_index(op.f('ix_farm_user_id'), 'farm', ['user_id'], unique=True)
    op.create_index(op.f('ix_farm_verification_status'), 'farm', ['verification_status'], unique=False)
    op.create_table('notification',
    sa.Column('notification_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('order', 'payment', 'delivery', 'promotion', 'system', native_enum=False, length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_items', JSONB_COL, nullable=False),
    sa.Column('order_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', 'confirmed', 'preparing', 'in_transit', 'delivered', 'cancelled', 'refunded', native_enum=False, length=40), nullable=False),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_order_status'), 'order', ['status'], unique=False)
    op.create_index(op.f('ix_order_user_id'), 'order', ['user_id'], unique=False)
    op.create_table('complaint',
    sa.Column('complaint_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_review', 'resolved', 'closed', native_enum=False, length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('complaint_id')
    )
    op.create_index(op.f('ix_complaint_order_id'), 'complaint', ['order_id'], unique=False)
    op.create_index(op.f('ix_complaint_status'), 'complaint', ['status'], unique=False)
    op.create_index(op.f('ix_complaint_user_id'), 'complaint', ['user_id'], unique=False)
    op.create_table('delivery',
    sa.Column('delivery_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('delivery_person_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'assigned', 'picked_up', 'in_transit', 'delivered', 'failed', native_enum=False, length=40), nullable=False),
    sa.ForeignKeyConstraint(['delivery_person_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
    sa.PrimaryKeyConstraint('delivery_id')
    )
    op.create_index(op.f('ix_delivery_delivery_person_id'), 'delivery', ['delivery_person_id'], unique=False)
    op.create_index(op.f('ix_delivery_order_id'), 'delivery', ['order_id'], unique=True)
    op.create_index(op.f('ix_delivery_status'), 'delivery', ['status'], unique=False)
    op.create_table('farm_analytics',
    sa.Column('analytics_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('product_category', sa.String(length=128), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('quantity_produced', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity_sold', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity_wasted', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('profit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('loss', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.farm_id'], ),
    sa.PrimaryKeyConstraint('analytics_id')
    )
    op.create_index(op.f('ix_farm_analytics_farm_id'), 'farm_analytics', ['farm_id'], unique=False)
    op.create_table('milk_batch',
    sa.Column('batch_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('batch_code', sa.String(length=64), nullable=False),
    sa.Column('milking_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('collection_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quantity_liters', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('initial_storage_temp', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('status', sa.Enum('recorded', 'testing', 'approved', 'rejected', 'expired', native_enum=False, length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.farm_id'], ),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_index(op.f('ix_milk_batch_batch_code'), 'milk_batch', ['batch_code'], unique=True)
    op.create_index(op.f('ix_milk_batch_farm_id'), 'milk_batch', ['farm_id'], unique=False)
    op.create_table('payment',
    sa.Column('payment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.Enum('card', 'bank_transfer', 'wallet', 'cash_on_delivery', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', 'refunded', native_enum=False, length=40), nullable=False),
    sa.Column('transaction_ref', sa.String(length=128), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
    sa.PrimaryKeyConstraint('payment_id'),
    sa.UniqueConstraint('transaction_ref')
    )
    op.create_index(op.f('ix_payment_order_id'), 'payment', ['order_id'], unique=True)
    op.create_table('ai_prediction',
    sa.Column('prediction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('predicted_shelf_life_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('freshness_score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('quality_class', sa.Enum('Fresh', 'Medium', 'Near Expiry', native_enum=False, length=40), nullable=True),
    sa.Column('anomaly_flag', sa.Boolean(), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('predicted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['milk_batch.batch_id'], ),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    op.create_index(op.f('ix_ai_prediction_batch_id'), 'ai_prediction', ['batch_id'], unique=False)
    op.create_table('delivery_tracking',
    sa.Column('tracking_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False),
    sa.Column('status_update', sa.String(length=512), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['delivery.delivery_id'], ),
    sa.PrimaryKeyConstraint('tracking_id')
    )
    op.create_index(op.f('ix_delivery_tracking_delivery_id'), 'delivery_tracking', ['delivery_id'], unique=False)
    op.create_table('iot_sensor_reading',
    sa.Column('reading_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('sensor_type', sa.String(length=64), nullable=False),
    sa.Column('reading_value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['milk_batch.batch_id'], ),
    sa.PrimaryKeyConstraint('reading_id')
    )
    op.create_index(op.f('ix_iot_sensor_reading_batch_id'), 'iot_sensor_reading', ['batch_id'], unique=False)
    op.create_index(op.f('ix_iot_sensor_reading_recorded_at'), 'iot_sensor_reading', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_iot_sensor_reading_sensor_type'), 'iot_sensor_reading', ['sensor_type'], unique=False)
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity_available', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'out_of_stock', 'archived', native_enum=False, length=40), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['milk_batch.batch_id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.farm_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_product_batch_id'), 'product', ['batch_id'], unique=False)
    op.create_index(op.f('ix_product_category'), 'product', ['category'], unique=False)
    op.create_index(op.f('ix_product_farm_id'), 'product', ['farm_id'], unique=False)
    op.create_index(op.f('ix_product_name'), 'product', ['name'], unique=False)
    op.create_table('bulk_purchase_request',
    sa.Column('request_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_requested', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('open', 'fulfilled', 'expired', 'cancelled', native_enum=False, length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index(op.f('ix_bulk_purchase_request_buyer_id'), 'bulk_purchase_request', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_bulk_purchase_request_product_id'), 'bulk_purchase_request', ['product_id'], unique=False)
    op.create_index(op.f('ix_bulk_purchase_request_status'), 'bulk_purchase_request', ['status'], unique=False)
    op.create_table('discount',
    sa.Column('discount_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.PrimaryKeyConstraint('discount_id')
    )
    op.create_index(op.f('ix_discount_product_id'), 'discount', ['product_id'], unique=False)
    op.create_table('price_history',
    sa.Column('history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('old_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('new_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_price_history_product_id'), 'price_history', ['product_id'], unique=False)
    op.create_table('review',
    sa.Column('review_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.farm_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_review_farm_id'), 'review', ['farm_id'], unique=False)
    op.create_index(op.f('ix_review_product_id'), 'review', ['product_id'], unique=False)
    op.create_index(op.f('ix_review_user_id'), 'review', ['user_id'], unique=False)
    op.create_table('subscription',
    sa.Column('subscription_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.Enum('daily', 'weekly', 'monthly', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', 'cancelled', native_enum=False, length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.farm_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('subscription_id')
    )
    op.create_index(op.f('ix_subscription_farm_id'), 'subscription', ['farm_id'], unique=False)
    op.create_index(op.f('ix_subscription_status'), 'subscription', ['status'], unique=False)
    op.create_index(op.f('ix_subscription_user_id'), 'subscription', ['user_id'], unique=False)
    op.create_table('quotation',
    sa.Column('quotation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('bid_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity_offered', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('submitted', 'accepted', 'rejected', 'withdrawn', native_enum=False, length=40), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.farm_id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['bulk_purchase_request.request_id'], ),
    sa.PrimaryKeyConstraint('quotation_id')
    )
    op.create_index(op.f('ix_quotation_farm_id'), 'quotation', ['farm_id'], unique=False)
    op.create_index(op.f('ix_quotation_request_id'), 'quotation', ['request_id'], unique=False)
    op.create_index(op.f('ix_quotation_status'), 'quotation', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotation_status'), table_name='quotation')
    op.drop_index(op.f('ix_quotation_request_id'), table_name='quotation')
    op.drop_index(op.f('ix_quotation_farm_id'), table_name='quotation')
    op.drop_table('quotation')
    op.drop_index(op.f('ix_subscription_user_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_status'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_farm_id'), table_name='subscription')
    op.drop_table('subscription')
    op.drop_index(op.f('ix_review_user_id'), table_name='review')
    op.drop_index(op.f('ix_review_product_id'), table_name='review')
    op.drop_index(op.f('ix_review_farm_id'), table_name='review')
    op.drop_table('review')
    op.drop_index(op.f('ix_price_history_product_id'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_discount_product_id'), table_name='discount')
    op.drop_table('discount')
    op.drop_index(op.f('ix_bulk_purchase_request_status'), table_name='bulk_purchase_request')
    op.drop_index(op.f('ix_bulk_purchase_request_product_id'), table_name='bulk_purchase_request')
    op.drop_index(op.f('ix_bulk_purchase_request_buyer_id'), table_name='bulk_purchase_request')
    op.drop_table('bulk_purchase_request')
    op.drop_index(op.f('ix_product_name'), table_name='product')
    op.drop_index(op.f('ix_product_farm_id'), table_name='product')
    op.drop_index(op.f('ix_product_category'), table_name='product')
    op.drop_index(op.f('ix_product_batch_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_iot_sensor_reading_sensor_type'), table_name='iot_sensor_reading')
    op.drop_index(op.f('ix_iot_sensor_reading_recorded_at'), table_name='iot_sensor_reading')
    op.drop_index(op.f('ix_iot_sensor_reading_batch_id'), table_name='iot_sensor_reading')
    op.drop_table('iot_sensor_reading')
    op.drop_index(op.f('ix_delivery_tracking_delivery_id'), table_name='delivery_tracking')
    op.drop_table('delivery_tracking')
    op.drop_index(op.f('ix_ai_prediction_batch_id'), table_name='ai_prediction')
    op.drop_table('ai_prediction')
    op.drop_index(op.f('ix_payment_order_id'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_milk_batch_farm_id'), table_name='milk_batch')
    op.drop_index(op.f('ix_milk_batch_batch_code'), table_name='milk_batch')
    op.drop_table('milk_batch')
    op.drop_index(op.f('ix_farm_analytics_farm_id'), table_name='farm_analytics')
    op.drop_table('farm_analytics')
    op.drop_index(op.f('ix_delivery_status'), table_name='delivery')
    op.drop_index(op.f('ix_delivery_order_id'), table_name='delivery')
    op.drop_index(op.f('ix_delivery_delivery_person_id'), table_name='delivery')
    op.drop_table('delivery')
    op.drop_index(op.f('ix_complaint_user_id'), table_name='complaint')
    op.drop_index(op.f('ix_complaint_status'), table_name='complaint')
    op.drop_index(op.f('ix_complaint_order_id'), table_name='complaint')
    op.drop_table('complaint')
    op.drop_index(op.f('ix_order_user_id'), table_name='order')
    op.drop_index(op.f('ix_order_status'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_farm_verification_status'), table_name='farm')
    op.drop_index(op.f('ix_farm_user_id'), table_name='farm')
    op.drop_table('farm')
    op.drop_index(op.f('ix_chatbot_message_user_id'), table_name='chatbot_message')
    op.drop_index(op.f('ix_chatbot_message_session_id'), table_name='chatbot_message')
    op.drop_table('chatbot_message')
    op.drop_index(op.f('ix_cart_user_id'), table_name='cart')
    op.drop_table('cart')
    op.drop_index(op.f('ix_admin_action_log_admin_id'), table_name='admin_action_log')
    op.drop_index(op.f('ix_admin_action_log_action'), table_name='admin_action_log')
    op.drop_table('admin_action_log')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
