import { Link } from "react-router-dom";
import { Milk, BadgeCheck, FlaskConical, Truck } from "lucide-react";
import {
  EditorialHero,
  HeroCta,
  ColourBlock,
  EditorialSectionHead,
} from "../../components/public/Editorial";
import { Reveal } from "../../components/ui/Reveal";
import { DEMO_LABELS } from "../../lib/constants";

const STAGES = [
  {
    title: "Milking at verified farms",
    text: "Partner farms milk on schedule and record every batch: time, quantity and initial storage temperature. Farms join only after identity, document and location verification.",
  },
  {
    title: "Batch data & collection",
    text: "Collection time, volume and storage conditions are saved with the batch so AI and IoT monitoring have a reliable data history.",
  },
  {
    title: "Quality & AI check",
    text: "Milk composition is screened for adulteration, and machine-learning models estimate remaining shelf life and spoilage risk from the batch's cold-chain data. Every result shows its confidence and is labelled as a demonstration estimate — never presented as laboratory certification.",
  },
  {
    title: "Monitored cold-chain delivery",
    text: "Refrigerated transport carries batches to their destinations while temperature sensors keep watch. Breaches and excursions are flagged automatically, and riders confirm each handoff.",
  },
  {
    title: "Delivered to the doorstep",
    text: "Delivery is confirmed at the final handoff, completing the monitored farm-to-doorstep journey.",
  },
];

const STAGE_ICONS = [Milk, BadgeCheck, FlaskConical, Truck, BadgeCheck];

const HONEST = [
  {
    label: DEMO_LABELS.iot,
    text: "Sensor readings in this demo are generated by our IoT simulator. The pipeline — ingestion, storage, dashboards — is real; the hardware feed is simulated.",
  },
  {
    label: DEMO_LABELS.ai,
    text: "Freshness scores come from trained models, but they are estimates for demonstration — not laboratory certification, and never a guarantee of shelf life.",
  },
];

export function HowItWorks() {
  return (
    <div>
      <EditorialHero
        eyebrow="How it works"
        title={"From our farms\nto your table"}
        lede="Five stages. One verifiable chain. Here's exactly what happens to milk inside the ApnaDairy network."
        actions={
          <>
            <HeroCta to="/freshness-engine" label="Explore the freshness engine" variant="light" />
          </>
        }
      />

      <ColourBlock tone="ivory">
        <EditorialSectionHead
          eyebrow="The chain"
          title="Five stages, fully traceable"
          lede="Each stage hands a verifiable record to the next — time-stamped, sensor-backed, and tied to one batch code."
        />
        <ol className="space-y-3">
          {STAGES.map((s, i) => {
            const Icon = STAGE_ICONS[i];
            return (
              <Reveal
                as="li"
                key={s.title}
                delay={Math.min(i * 0.05, 0.25)}
                className="grid gap-4 rounded-2xl border border-line bg-white p-6 shadow-card sm:grid-cols-[auto_1fr] sm:gap-8 sm:p-8"
              >
                <div className="flex items-center gap-4 sm:flex-col sm:items-start">
                  <span className="flex h-14 w-14 items-center justify-center rounded-2xl bg-mint text-brand-pine">
                    <Icon className="h-7 w-7" aria-hidden="true" />
                  </span>
                  <span
                    aria-hidden="true"
                    className="font-condensed text-5xl leading-none text-brand/15"
                  >
                    {String(i + 1).padStart(2, "0")}
                  </span>
                </div>
                <div>
                  <h2 className="font-condensed text-3xl uppercase leading-[0.95] text-ink sm:text-4xl">
                    {s.title}
                  </h2>
                  <p className="mt-3 max-w-3xl leading-relaxed text-muted">{s.text}</p>
                </div>
              </Reveal>
            );
          })}
        </ol>
      </ColourBlock>

      <ColourBlock tone="forest">
        <EditorialSectionHead
          dark
          eyebrow="Honest by design"
          title="What we label, and why"
          lede="A demo should never pretend to be a laboratory. Wherever data is simulated or estimated, we say so — right next to the number."
        />
        <div className="grid gap-4 md:grid-cols-3">
          {HONEST.map((c) => (
            <Reveal
              key={c.label}
              className="rounded-2xl border border-white/10 bg-white/[0.06] p-6 sm:p-7"
            >
              <p className="text-xs font-bold uppercase tracking-[0.18em] text-[#DDF06A]">
                {c.label}
              </p>
              <p className="mt-3 text-sm leading-relaxed text-ivory/70">{c.text}</p>
            </Reveal>
          ))}
        </div>
        <Reveal className="mt-10 flex flex-wrap gap-3">
          <Link
            to="/freshness-engine"
            className="btn-lift inline-flex h-12 items-center rounded-full bg-[#DDF06A] px-7 text-sm font-semibold text-brand-forest hover:brightness-105"
          >
            Explore the freshness engine
          </Link>
        </Reveal>
      </ColourBlock>

    </div>
  );
}
